/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author Douglas
 */
public class Interfaz extends javax.swing.JFrame {
    
    /**
     * Creates new form Interfaz
     */
    
//    Objeto de la clase hora
    Hora horario = new Hora();
//    Arraylist donde se almacenarán los procesos para dejarlo simple
    ArrayList<Proceso> Procesos = new ArrayList();    
//    Arraylist donde se almacenarán los rectángulos a pintar (class Rectangle)
    ArrayList<Rectangle> Rectangulos = new ArrayList();    
//    Objero para crear un numero random  
    Random rand = new Random();
//    Cantidad de procesos creados
    int nProcesos = 0;  
//    Variables de prueba
    int xAxis = 0, yAxis = 0;
    
    public Interfaz() {
        horario.start();
        initComponents();
        
    }
    
    public class Hora extends Thread {
        
        boolean stop = true;
        @Override      
        public void run(){
                while (stop){
                    //    Cada segundo se crea objeto de la clase date, que obtiene la hora exacta en la que se crea
                    Date date = new Date();
                    DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");
                    Hora.setText(dateFormat.format(date));                  
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMemoria = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelMemoria.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMemoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Crear proceso");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Borrar primero");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Hora");

        jButton3.setText("Imprimir ArrayList");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addGap(60, 60, 60))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabelMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //
        // AVANZAR CON HACERLOS DE TAMAÑOS ALEATORIOS (Entre 5 y 30 px de alto)
        int randomN = (int) (Math.random() * (100 - 30 + 1) + 5);
        //
        // Se crea un nuevo proceso cada vez que se presiona el botón, se almacena en :
        
        // Se debe ver que si no se puede crear el proceso restar 1 a nProcesos y eliminar
        // la entrada del arraylist
        
        nProcesos++;
//        Compara si la lista de procesos está vacía, de ser así solo añade el proceso sin siguiente
//        En caso de no ser el primero, asigna al anterior que el nuevo será el siguiente, y el nuevo
//        Apuntará al primero que se encuentra en el index 0
        if(Procesos.isEmpty()){
            Proceso Proces0 = new Proceso(nProcesos, randomN, 0, 0, 0, null);
            Procesos.add(Proces0);
        }else{
            Proceso Proces0 = new Proceso(nProcesos, randomN, 0, 0, 0, Procesos.get(0));
            Procesos.get(Procesos.size()-1).setSiguiente(Proces0);
            Procesos.add(Proces0);
        }
        // También se añade un rectanguo para pintar (Pruebas)
        int randSpot = lookForAvaliableSpot(randomN);        
        Rectangulos.add(new Rectangle(60,randSpot,119,randomN));
        // Se llama al método repaint para pintar de nuevo todos los rectangulos en el arraylist
        repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Pruebas de rectángulos:
        Procesos.remove(0);
        Rectangulos.remove(0);
        Procesos.get(Procesos.size()-1).setSiguiente(Procesos.get(0));
        repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<Procesos.size();i++){
            System.out.println("--------- Proceso no. " + i + " ---------");
            System.out.println("Identificador: " + Procesos.get(i).getIdentificador());
            System.out.println("Tamaño: " + Procesos.get(i).getTamaño());
            System.out.println("LowerSpot: " + Procesos.get(i).getRegistroBase());
            System.out.println("HigherSpot: " + Procesos.get(i).getRegistroLimite());
            if(Procesos.size()>1){
                System.out.println("El proceso siguiente es: " + Procesos.get(i).getSiguiente().getIdentificador());
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    int randomS=0;
    int pxLower=0;
    int pxHigher=0;
    boolean avaliable;
    public int lookForAvaliableSpot(int rectangleSize){
        System.out.println("-----Nuevo-----");
        avaliable = true;
        // Los valores para agregar procesos están entre 102-496
        randomS = (int) (Math.random() * (496 - 102 + 1) + 102);
        pxLower = randomS; System.out.println(pxLower);
        pxHigher = randomS + rectangleSize; System.out.println(pxHigher);
        System.out.println("El valor de la bandera es " + avaliable);
        for(int i=0; i<Procesos.size()-1;i++){
            
            // El nuevo cuadro no está contenido en uno ya creado
            
            if(pxLower >= Procesos.get(i).getRegistroBase() && pxLower <= Procesos.get(i).getRegistroLimite()){
                System.out.println("El limite inferior interfiere");
                System.out.println(Procesos.get(i).getRegistroBase());
                System.out.println(Procesos.get(i).getRegistroLimite());
                System.out.println(pxLower);
                avaliable = false;
            }
            else if(pxHigher >= Procesos.get(i).getRegistroBase() && pxHigher <= Procesos.get(i).getRegistroLimite()){
                System.out.println("El limite superior interfiere");
                System.out.println(Procesos.get(i).getRegistroBase());
                System.out.println(Procesos.get(i).getRegistroLimite());
                System.out.println(pxHigher);
                avaliable = false;
            }
            
            // El nuevo cuadro no contiene uno ya creado
            
            else if(Procesos.get(i).getRegistroBase() >= pxLower && Procesos.get(i).getRegistroBase() <= pxHigher){
                System.out.println("El limite inferior de un cuadro existente interfiere");
                System.out.println(Procesos.get(i).getRegistroBase());
                System.out.println(Procesos.get(i).getRegistroLimite());
                System.out.println(pxLower);
                avaliable = false;
            }
            
            else if(Procesos.get(i).getRegistroLimite() >= pxLower && Procesos.get(i).getRegistroLimite() <= pxHigher){
                System.out.println("El limite superior de un cuadro existente interfiere");
                System.out.println(Procesos.get(i).getRegistroBase());
                System.out.println(Procesos.get(i).getRegistroLimite());
                System.out.println(pxLower);
                avaliable = false;
            }
            
            if(avaliable==false){
                break;
            }
        }
        System.out.println("El valor de la bandera es " + avaliable);
        if(avaliable==true){
            //Acá se agregan los atributos de registro base y límite para el planificador
            Procesos.get(Procesos.size()-1).setRegistroBase(pxLower);
            Procesos.get(Procesos.size()-1).setRegistroLimite(pxHigher);
            return randomS;
        }else{
            System.out.println(avaliable);
            System.out.println("Se hará de nuevo por fallo"); 
            lookForAvaliableSpot(rectangleSize);
        }
        System.out.println("finalizó");
        return randomS;
    }
    
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    
    
    public void paint(Graphics g)
    {
        super.paint(g);
        // Pinta los rectángulos que están en el arraylist
        for(int i=0; i<Rectangulos.size();i++){
//            int int_random = rand.nextInt(5); 
//            switch(int_random) {
//                case 0:
//                  g.setColor(Color.BLUE);
//                  break;
//                case 1:
//                  g.setColor(Color.RED);
//                  break;
//                case 2:
//                  g.setColor(Color.YELLOW);
//                  break;
//                case 3:
//                  g.setColor(Color.GREEN);
//                  break;
//                case 4:
//                  g.setColor(Color.orange);
//                  break;
//                default:
//                  // code block
//            }
            g.setColor(Color.orange);
            g.fillRect(Rectangulos.get(i).x, Rectangulos.get(i).y, Rectangulos.get(i).width, Rectangulos.get(i).height);
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hora;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMemoria;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
